/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with username and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthEnvelope"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Rotated token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthEnvelope"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible tasks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                tasks?: components["schemas"]["Task"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description Created task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Task"];
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim the next available task item */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Claimed task bundle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["TaskBundle"];
                        };
                    };
                };
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/items/{itemId}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a draft answer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["AnswerBody"];
            responses: {
                200: components["responses"]["Submission"];
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/items/{itemId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an answer for AI or human review */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["AnswerBody"];
            responses: {
                200: components["responses"]["Submission"];
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviewer/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions waiting for reviewer action */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                submissions?: components["schemas"]["Submission"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviewer/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load reviewer submission detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submissionId: components["parameters"]["SubmissionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Submission detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["SubmissionDetail"];
                        };
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve, reject, or request revision */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submissionId: components["parameters"]["SubmissionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewRequest"];
                };
            };
            responses: {
                200: components["responses"]["Submission"];
                400: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List task template versions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                templates?: components["schemas"]["TaskTemplate"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Save a new task template version */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateSchema"];
                };
            };
            responses: {
                /** @description Created template */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["TaskTemplate"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load a template version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                template?: components["schemas"]["TaskTemplate"];
                                isLatest?: boolean;
                                latestTemplateId?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List export jobs for a task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Export jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                exports?: components["schemas"]["ExportJob"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an async export job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExportRequest"];
                };
            };
            responses: {
                /** @description Queued export job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                id?: number;
                                status?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/exports/{exportId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Create a signed export download URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                    exportId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                url?: string;
                                expiresIn?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load owner task statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["TaskStats"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            data: Record<string, never>;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthEnvelope: components["schemas"]["Envelope"] & {
            data?: {
                accessToken: string;
                refreshToken: string;
                user: components["schemas"]["User"];
            };
        };
        User: {
            id: number;
            username: string;
            displayName?: string;
            roles: string[];
        };
        Task: {
            id: number;
            ownerId: number;
            title: string;
            status: string;
            aiReviewEnabled?: boolean;
            humanReviewEnabled?: boolean;
            totalItems?: number;
            finishedItems?: number;
        };
        CreateTaskRequest: {
            title: string;
            description?: string;
            tags?: string[];
        };
        TaskItem: {
            id: number;
            taskId: number;
            externalId?: string | null;
            payload: {
                [key: string]: unknown;
            } | string;
            status: string;
        };
        TaskTemplate: {
            id: number;
            taskId: number;
            version: number;
            schemaJson: string;
        };
        TemplateSchema: {
            title: string;
            /** @enum {string} */
            layout?: "single_page";
            fields: {
                [key: string]: unknown;
            }[];
            export_fields?: string[];
        } & {
            [key: string]: unknown;
        };
        TaskBundle: {
            task: components["schemas"]["Task"];
            item: components["schemas"]["TaskItem"];
            template: components["schemas"]["TaskTemplate"];
            submission?: components["schemas"]["Submission"];
            revision?: components["schemas"]["SubmissionRevision"];
        };
        Submission: {
            id: number;
            taskId: number;
            itemId: number;
            /** @enum {string} */
            status: "draft" | "submitted" | "ai_reviewing" | "human_reviewing" | "revising" | "approved" | "rejected";
            currentRevisionId?: number | null;
            /** @enum {string|null} */
            aiVerdict?: "pass" | "reject" | "uncertain" | null;
            aiScore?: number | null;
            /** @enum {string|null} */
            humanVerdict?: "approve" | "reject" | "revise" | null;
        };
        SubmissionRevision: {
            id?: number;
            submissionId?: number;
            revisionNo?: number;
            answer?: string;
        };
        SubmissionDetail: {
            submission?: components["schemas"]["Submission"];
            item?: components["schemas"]["TaskItem"];
            template?: components["schemas"]["TaskTemplate"];
            revision?: components["schemas"]["SubmissionRevision"];
            aiReview?: {
                [key: string]: unknown;
            };
            auditLogs?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        ReviewRequest: {
            /** @enum {string} */
            verdict: "approve" | "reject" | "revise";
            reason?: string;
        };
        CreateExportRequest: {
            /** @enum {string} */
            format: "json" | "jsonl" | "csv" | "xlsx";
            field_map?: {
                [key: string]: unknown;
            } | null;
            include_reviews?: boolean;
        };
        ExportJob: {
            id?: number;
            taskId?: number;
            format?: string;
            status?: string;
            rowCount?: number | null;
            fileSize?: number | null;
            errorMsg?: string | null;
        };
        TaskStats: {
            progress?: {
                total?: number;
                finished?: number;
            };
            statusBreakdown?: {
                [key: string]: number;
            };
            passRate?: number;
            aiVsHuman?: {
                compared?: number;
                disagree?: number;
                rate?: number;
            };
            dimensionAverages?: {
                name?: string;
                avg?: number;
            }[];
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Submission snapshot */
        Submission: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Submission"];
                };
            };
        };
    };
    parameters: {
        TaskId: number;
        ItemId: number;
        SubmissionId: number;
    };
    requestBodies: {
        AnswerBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
